# Promtail configuration
# Try to use Helm Chart default configuration, only override necessary settings

# Configure Promtail to connect to Loki
config:
  clients:
    - url: http://loki.monitoring.svc:3100/loki/api/v1/push

